---
- name: create a group
  group:
     name: tomcat
     state: present

- name: create a user
  user:
    name: tomcat
    home: /opt/tomcat
    group: tomcat
    shell: /bin/false
    state: present
