---
- name: create a directory
  file:
    path: /opt/tomcat
    state: directory
    mode: 0755

- name: extract Tomcat to the /opt/tomcat directory
  command: 
     cmd: sudo tar xzvf /home/ubuntu/apache-tomcat-8.5.5.tar.gz -C /opt/tomcat --strip-components=1
     creates: /opt/tomcat/LICENSE